/**
 * Custom Worker entrypoint.
 *
 * Wraps the Worker generated by `opennextjs-cloudflare build` so a cron handler can
 * live next to the Next.js fetch handler. The cron exists for one reason: Supabase
 * pauses free-tier projects after a week without database activity, which takes the
 * whole app down until someone clicks "Resume" in the dashboard.
 *
 * Excluded from tsconfig — `./.open-next/worker.js` only exists after a build.
 */
import handler from './.open-next/worker.js'

type KeepAliveEnv = {
  NEXT_PUBLIC_SUPABASE_URL: string
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string
}

type ExecutionCtx = {
  waitUntil(promise: Promise<unknown>): void
}

/**
 * Runs a real SELECT through PostgREST. `/auth/v1/health` is not enough — it answers
 * without touching Postgres, so it does not count as activity. RLS gives the anon role
 * an empty array (policies filter by `user_id = public.current_user_id()`, and
 * `auth.uid()` is null here), so the 200 is the signal, not the payload.
 */
async function keepDatabaseAwake(env: KeepAliveEnv): Promise<void> {
  const base = env.NEXT_PUBLIC_SUPABASE_URL.replace(/\/$/, '')
  const res = await fetch(`${base}/rest/v1/recipes?select=id&limit=1`, {
    headers: {
      apikey: env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      Authorization: `Bearer ${env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
    },
  })

  if (!res.ok) {
    console.error(`keep-alive: Supabase responded ${res.status}`)
    return
  }
  console.log('keep-alive: Supabase database reached')
}

const worker = {
  fetch: handler.fetch,

  async scheduled(_controller: unknown, env: KeepAliveEnv, ctx: ExecutionCtx): Promise<void> {
    ctx.waitUntil(keepDatabaseAwake(env))
  },
}

export default worker
