/**
 * Custom Worker entrypoint.
 *
 * Wraps the Worker generated by `opennextjs-cloudflare build` so cron handlers can
 * live next to the Next.js fetch handler. Two crons run here, declared in
 * wrangler.jsonc and dispatched below by which one fired:
 *
 *   keep-alive — Supabase pauses free-tier projects after a week without database
 *                activity, which takes the whole app down until someone clicks
 *                Resume in the dashboard.
 *   backup     — the free plan includes no backups, so the recipes exist in exactly
 *                one place. This copies them to R2 daily.
 *
 * The backup also counts as database activity, so on a good day it keeps the project
 * awake by itself. keep-alive stays as the fallback for when the backup is broken —
 * a missing secret should cost us a backup, not the whole app.
 *
 * The jobs themselves live in src/lib/worker-cron.ts so they can be typechecked and
 * tested. This file is excluded from tsconfig: `./.open-next/worker.js` only exists
 * after a build, so nothing here can be, and it is kept as thin as possible.
 */
import handler from './.open-next/worker.js'
import { backupToR2, keepDatabaseAwake, type CronEnv } from './src/lib/worker-cron'

const KEEP_ALIVE_CRON = '0 4 * * *'
const BACKUP_CRON = '30 3 * * *'

type ScheduledController = {
  cron: string
}

type ExecutionCtx = {
  waitUntil(promise: Promise<unknown>): void
}

const worker = {
  fetch: handler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: CronEnv,
    ctx: ExecutionCtx,
  ): Promise<void> {
    switch (controller.cron) {
      case BACKUP_CRON:
        ctx.waitUntil(backupToR2(env))
        return
      case KEEP_ALIVE_CRON:
        ctx.waitUntil(keepDatabaseAwake(env))
        return
      default:
        console.error(`scheduled: no handler for cron "${controller.cron}"`)
    }
  },
}

export default worker
